[connect-base]
certPath = ""
keyPath = ""

[connect-websocket]
#serverId = "1000"
bind = "0.0.0.0:7071"

[connect-tcp]
#serverId = "2000"
bind = "0.0.0.0:7072,0.0.0.0:7073"
sendbuf = 4096
receivebuf = 4096
keepalive = false
reader = 32
readBuf = 1024
readBufSize = 8192
writer = 32
writeBuf = 1024
writeBufSize = 8192

[connect-rpcAddress-websockts]
address = "tcp@0.0.0.0:7075,tcp@0.0.0.0:7075"


[connect-rpcAddress-tcp]
address = "tcp@0.0.0.0:7076,tcp@0.0.0.0:7077"

[connect-bucket]
cpuNum = 4
channel = 1024
room = 1024
svrProto = 80
routineAmount = 32
routineSize = 20




