// Code generated by goctl. DO NOT EDIT!
// Source: conn.proto

package server

import (
	"context"

	"imservice/app/conn/internal/logic"
	"imservice/app/conn/internal/svc"
	"imservice/common/pb"
)

type ConnServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedConnServiceServer
}

func NewConnServiceServer(svcCtx *svc.ServiceContext) *ConnServiceServer {
	return &ConnServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ConnServiceServer) KickUserConn(ctx context.Context, in *pb.KickUserConnReq) (*pb.KickUserConnResp, error) {
	l := logic.NewKickUserConnLogic(ctx, s.svcCtx)
	return l.KickUserConn(in)
}

func (s *ConnServiceServer) GetUserConn(ctx context.Context, in *pb.GetUserConnReq) (*pb.GetUserConnResp, error) {
	l := logic.NewGetUserConnLogic(ctx, s.svcCtx)
	return l.GetUserConn(in)
}

func (s *ConnServiceServer) SendMsg(ctx context.Context, in *pb.SendMsgReq) (*pb.SendMsgResp, error) {
	l := logic.NewSendMsgLogic(ctx, s.svcCtx)
	return l.SendMsg(in)
}

func (s *ConnServiceServer) KeepAlive(ctx context.Context, in *pb.KeepAliveReq) (*pb.KeepAliveResp, error) {
	l := logic.NewKeepAliveLogic(ctx, s.svcCtx)
	return l.KeepAlive(in)
}
