appName = "chat_room"
appMode = "pro"
appHost = ""
appPort = 9788

[mysql]
host = "mysql"
name = "app_chat"
password = "bdaffa037a6b11d5"
port = 3306
tablePrefix = ""
user = "root"

[log]
level = "debug"
path = "deploy/logs/chat.log"

[staticPath]
filePath = "deploy/static/file/"

[msgChannelType]
channelType = "gochannel"

kafkaHosts = "kafka:9092"
kafkaTopic = "go-chat-message"