[common-etcd]
host = "etcd:2379"
basePath = "/gochat_srv"
serverPathLogic = "LogicRpc"
serverPathConnect = "ConnectRpc"
userName = ""
password = ""
connectionTimeout = 5

[common-redis]
redisAddress = "redis:6379"
redisPassword = "bdaffa037a6b11d5"
db = 0